services:
  api:
    build:
      context: ./api
    environment:
      - NODE_ENV=production
      - PORT=3000
      - APP_VERSION=local
    ports:
      - "3000:3000"

  web:
    build:
      context: ./web
    ports:
      - "8080:8080"
    depends_on:
      - api